name: CI / Content Verification

on:
  pull_request:
    branches:
      - "**"

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install pnpm
        run: npm install -g pnpm@10.0.0 && pnpm setup && pnpm -v

      - name: Install dependencies
        run: pnpm i

      - name: Run Tests
        id: tests
        run: |
          set +e
          pnpm test > test-results.txt 2>&1
          echo "exit_code=$?" >> $GITHUB_ENV
          cat test-results.txt

      - name: Install strip-ansi-cli
        run: pnpm add -g strip-ansi-cli

      - name: Run Build
        id: build
        run: |
            FORCE_COLOR=1 pnpm run build 2>&1 | tee build-full.txt
            tail -n 30 build-full.txt > build-info-ansi.txt
            strip-ansi build-info-ansi.txt > build-info.txt
            echo "BUILD_LOG<<EOF" >> $GITHUB_ENV
            cat build-info.txt >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
        

      - name: Create or Update PR Comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.BOT_TOKEN || secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## 📦 Bundle Log

            ```ansi
            ${{ env.BUILD_LOG_RAW }}
            ```

            ```log
            ${{ env.BUILD_LOG_RAW }}
            ```
            ---
            ✅ Built succeeded with **pnpm@10.0.0**, **Node.js 22**, and **Vite**.

            _Posted automatically by CI Bot._
